package main

type dataOperations struct {
	Select bool
	Insert bool
	Update bool
	Delete bool
}

var serverlessDataTables = map[string]dataOperations{
	"profiles":                     {Select: true, Insert: true, Update: true},
	"organizations":                {Select: true, Insert: true, Update: true},
	"locations":                    {Select: true, Insert: true, Update: true},
	"organization_members":         {Select: true, Insert: true, Update: true, Delete: true},
	"organization_invites":         {Select: true, Insert: true, Update: true, Delete: true},
	"staff":                        {Select: true, Insert: true, Update: true, Delete: true},
	"staff_time_entries":           {Select: true, Insert: true, Update: true},
	"staff_shifts":                 {Select: true, Insert: true, Update: true, Delete: true},
	"staff_attendance_summary":     {Select: true},
	"customers":                    {Select: true, Insert: true, Update: true},
	"customer_addresses":           {Select: true, Insert: true, Update: true, Delete: true},
	"categories":                   {Select: true, Insert: true, Update: true, Delete: true},
	"items":                        {Select: true, Insert: true, Update: true, Delete: true},
	"delivery_drivers":             {Select: true, Insert: true, Update: true, Delete: true},
	"driver_locations":             {Select: true, Insert: true},
	"orders":                       {Select: true, Insert: true, Update: true},
	"order_payments":               {Select: true, Insert: true, Update: true},
	"order_items":                  {Select: true, Insert: true, Update: true},
	"order_item_modifiers":         {Select: true, Insert: true},
	"driver_ratings":               {Select: true, Insert: true},
	"driver_earnings":              {Select: true, Insert: true, Update: true},
	"notifications":                {Select: true, Insert: true, Update: true},
	"bots":                         {Select: true, Insert: true, Update: true, Delete: true},
	"chats":                        {Select: true, Insert: true, Update: true, Delete: true},
	"messages":                     {Select: true, Insert: true, Update: true},
	"inventory_items":              {Select: true, Insert: true, Update: true, Delete: true},
	"stock_movements":              {Select: true, Insert: true},
	"tax_rates":                    {Select: true, Insert: true, Update: true, Delete: true},
	"reviews":                      {Select: true, Insert: true, Update: true},
	"item_recipes":                 {Select: true, Insert: true, Update: true, Delete: true},
	"item_prep_steps":              {Select: true, Insert: true, Update: true, Delete: true},
	"recipe_breakdown":             {Select: true},
	"recipe_summary":               {Select: true},
	"sections":                     {Select: true, Insert: true, Update: true, Delete: true},
	"tables":                       {Select: true, Insert: true, Update: true, Delete: true},
	"table_sessions":               {Select: true, Insert: true, Update: true},
	"seats":                        {Select: true, Insert: true, Update: true, Delete: true},
	"check_splits":                 {Select: true, Insert: true, Update: true, Delete: true},
	"check_split_items":            {Select: true, Insert: true, Update: true, Delete: true},
	"kitchen_stations":             {Select: true, Insert: true, Update: true, Delete: true},
	"category_station_routing":     {Select: true, Insert: true, Update: true, Delete: true},
	"item_station_routing":         {Select: true, Insert: true, Update: true, Delete: true},
	"kds_display_groups":           {Select: true, Insert: true, Update: true, Delete: true},
	"kds_tickets":                  {Select: true, Insert: true, Update: true},
	"kds_ticket_items":             {Select: true, Insert: true, Update: true},
	"kds_ticket_events":            {Select: true, Insert: true},
	"cash_drawers":                 {Select: true, Insert: true, Update: true, Delete: true},
	"cash_drawer_sessions":         {Select: true, Insert: true, Update: true},
	"cash_drawer_movements":        {Select: true, Insert: true},
	"cash_drawer_counts":           {Select: true, Insert: true},
	"cash_drawer_session_payments": {Select: true, Insert: true},
	"adjustment_reasons":           {Select: true, Insert: true, Update: true, Delete: true},
	"order_adjustments":            {Select: true, Insert: true, Update: true},
	"promotions":                   {Select: true, Insert: true, Update: true, Delete: true},
	"promotion_target_items":       {Select: true, Insert: true, Delete: true},
	"promotion_target_categories":  {Select: true, Insert: true, Delete: true},
	"coupon_codes":                 {Select: true, Insert: true, Update: true, Delete: true},
	"promotion_redemptions":        {Select: true, Insert: true},
	"order_item_discounts":         {Select: true, Insert: true},
	"suppliers":                    {Select: true, Insert: true, Update: true, Delete: true},
	"supplier_contacts":            {Select: true, Insert: true, Update: true, Delete: true},
	"supplier_locations":           {Select: true, Insert: true, Update: true, Delete: true},
	"supplier_inventory_items":     {Select: true, Insert: true, Update: true, Delete: true},
	"purchase_orders":              {Select: true, Insert: true, Update: true, Delete: true},
	"purchase_order_items":         {Select: true, Insert: true, Update: true, Delete: true},
	"goods_receipts":               {Select: true, Insert: true, Update: true},
	"goods_receipt_items":          {Select: true, Insert: true, Update: true},
	"supplier_invoices":            {Select: true, Insert: true, Update: true},
	"supplier_invoice_lines":       {Select: true, Insert: true, Update: true, Delete: true},
	"ingredient_price_history":     {Select: true, Insert: true},
	"daily_sales_summary":          {Select: true},
	"hourly_sales_heatmap":         {Select: true},
	"menu_engineering":             {Select: true},
	"labor_hours_daily":            {Select: true},
	"theoretical_vs_actual_cogs":   {Select: true},
	"revenue_by_payment_method":    {Select: true},
	"audit_log":                    {Select: true},
	"idempotency_keys":             {Select: true},
	"allergens":                    {Select: true, Insert: true, Update: true, Delete: true},
	"item_allergens":               {Select: true, Insert: true, Delete: true},
	"dietary_tags":                 {Select: true, Insert: true, Update: true, Delete: true},
	"item_dietary_tags":            {Select: true, Insert: true, Delete: true},
	"menu_schedules":               {Select: true, Insert: true, Update: true, Delete: true},
	"menu_schedule_slots":          {Select: true, Insert: true, Update: true, Delete: true},
	"item_menu_schedules":          {Select: true, Insert: true, Delete: true},
	"item_price_schedules":         {Select: true, Insert: true, Update: true, Delete: true},
	"gift_cards":                   {Select: true, Insert: true, Update: true},
	"gift_card_transactions":       {Select: true},
	"store_credits":                {Select: true},
	"store_credit_transactions":    {Select: true},
	"house_accounts":               {Select: true, Insert: true, Update: true, Delete: true},
	"house_account_members":        {Select: true, Insert: true, Update: true, Delete: true},
	"house_account_charges":        {Select: true},
	"house_account_invoices":       {Select: true, Insert: true, Update: true},
	"loyalty_config":               {Select: true, Insert: true, Update: true},
	"loyalty_transactions":         {Select: true},
	"customer_loyalty_stamps":      {Select: true, Insert: true, Update: true},
	"staff_pay_rates":              {Select: true, Insert: true, Update: true, Delete: true},
	"modifier_groups":              {Select: true, Insert: true, Update: true, Delete: true},
	"modifiers":                    {Select: true, Insert: true, Update: true, Delete: true},
	"courses":                      {Select: true, Insert: true, Update: true, Delete: true},
}
